os: linux

sudo: required

services: docker

language: go

jobs:
  include:
    - name: "Docker up"
      script:
        - docker-compose build
        - docker-compose up -d

notifications:
  email: false