os: linux

sudo: required

services: docker

go:
  - "1.12"
  - master

env:
  - GO111MODULE=on

jobs:
  include:
    - name: "Docker Up"
      script:
        - docker-compose build
        - docker-compose up -d
        - sh scripts/test.sh

notifications:
  email: false
