os: linux

sudo: required

services: docker

language: go
go:
  - "1.7"
#  - master

env:
  global:
    GO111MODULE: "on"

jobs:
  include:
    - name: "Docker Up"
      script:
        - docker-compose build
        - docker-compose up -d

notifications:
  email: false
