version: "3"
services:
  db:
    image: postgres
    container_name: todo_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      # TODO: Change it to environment variables
      POSTGRES_USER: aaaaaaaalesha
      POSTGRES_DB: todownik
      POSTGRES_PASSWORD: Qwerty12345!
  server:
    container_name: todoapp
    depends_on:
      - db
    build: .
    restart: always
    ports:
      - 8080:8080
    environment:
      # TODO: Change it to environment variables
      DB_NAME: todownik
      DB_USERNAME: aaaaaaaalesha
      DB_PASSWORD: Qwerty12345!

  bot:
    depends_on:
      - server
    build:
      ./src/telegram_bot
    environment:
      BOT_TOKEN:
    restart: always
