[[constraint]]
  name = "github.com/Syfaro/telegram-bot-api"
  version = "5.0.1"

[[constraint]]
  name = "github.com/briandowns/openweathermap"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-ozzo/ozzo-validation"
  version = "3.6.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.8.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.8.0"
