package user

const (
	START = iota // START = 0
	// FastTask.
	FAST_TASK_ENTER_TITLE
	FAST_TASK_ENTER_INTERVAL
	FAST_TASK_DELETE
	// Schedule.
	SCHEDULE_FILL_MON
	SCHEDULE_FILL_TUE
	SCHEDULE_FILL_WED
	SCHEDULE_FILL_THU
	SCHEDULE_FILL_FRI
	SCHEDULE_FILL_SAT
	SCHEDULE_FILL_SUN
	SCHEDULE_ENTER_TITLE
	SCHEDULE_ENTER_PLACE
	SCHEDULE_ENTER_SPEAKER
	SCHEDULE_ENTER_START
	SCHEDULE_ENTER_END
	SCHEDULE_ENTER_OUTPUT_WEEKDAY
	SCHEDULE_DELETE_TASK
	SCHEDULE_DELETE_CLEARALL
)
