name: Test

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build
        run: go build

      - name: Test and coverage
        run: |
          go test ./... -cover -coverprofile=profile.out
          go tool cover -html=profile.out -o=coverage.html

      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: coverage.html
          path: coverage.html
